const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
const USER_SIGNIN_ERROR = "USER_SIGNIN_ERROR";
const USER_LOGOUT = "USER_LOGOUT";

export {
    USER_SIGNIN_ERROR,
     USER_SIGNIN_SUCCESS,
     USER_SIGNIN_REQUEST,
     USER_LOGOUT
}